pyspark metrics:
uberkinder/Pure-Data pull request #13
Opened 2023-07-26 14:45 UTC by dvoykov

- implementations for CountFewLastDayRows, CheckAdversarialValidation
 - rework for CountNull, CountLastDayRows
 - changed test results for CheckAdversarialValidation

2023-07-26 15:15 UTC, IgnatovN requested changes

2023-07-26 15:15 UTC, IgnatovN commented on pure/metrics.py
> +        # columns differences/importances
Убрать комментарий

2023-07-26 15:15 UTC, IgnatovN commented on pure/metrics.py
>          # check for existence of numeric values
Убрать комментарий

2023-07-27 12:09 UTC, dvoykov commented on pure/metrics.py
> +        # asc sorted daily rows qty
done.

2023-07-27 12:09 UTC, dvoykov commented on pure/metrics.py
> +        # cross validation, binary classifier
done.

2023-07-27 12:10 UTC, dvoykov commented on pure/metrics.py
> +        # columns differences/importances
done.

2023-07-27 12:10 UTC, dvoykov commented on pure/metrics.py
> +        # try to slice df
done.

2023-07-27 12:10 UTC, dvoykov commented on pure/metrics.py
>          # check for slices overlap
done.

2023-07-27 12:10 UTC, dvoykov commented on pure/metrics.py
>          # check for existence of numeric values
done.

2023-07-27 12:10 UTC, dvoykov commented on pure/metrics.py
> +        # fill na values by global minimum minus 1000
done.

2023-07-27 12:11 UTC, IgnatovN approved these changes

2023-07-27 12:12 UTC, dvoykov commented on pure/metrics.py
> +        # empty(nan, null) columns count for each row
done.

2023-07-27 12:12 UTC, dvoykov commented on pure/metrics.py
>          # try to slice df
done.

2023-07-27 12:12 UTC, dvoykov commented on pure/metrics.py
> +        # check for existence of numeric values
done.

2023-07-31 12:29 UTC, merged